"""Job

Revision ID: 11b134d0e18c
Revises: dc57cb2d315a
Create Date: 2023-04-14 14:45:40.208732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11b134d0e18c'
down_revision = 'dc57cb2d315a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('requirement', sa.Text(), nullable=False),
    sa.Column('salary', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('available', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_title'), ['title'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_updated_at'), ['updated_at'], unique=False)

    op.create_table('job_category',
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], )
    )
    op.create_table('job_location',
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], )
    )
    op.drop_table('job_categories')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_categories',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='job_categories_pkey')
    )
    op.drop_table('job_location')
    op.drop_table('job_category')
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_updated_at'))
        batch_op.drop_index(batch_op.f('ix_job_title'))
        batch_op.drop_index(batch_op.f('ix_job_created_at'))

    op.drop_table('job')
    op.drop_table('category')
    # ### end Alembic commands ###
