"""job apply name added

Revision ID: 454ca0027626
Revises: 7bb9d6ce548f
Create Date: 2023-04-24 13:24:17.645602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '454ca0027626'
down_revision = '7bb9d6ce548f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_application', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=128), nullable=True))
        batch_op.create_index(batch_op.f('ix_job_application_name'), ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_application', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_application_name'))
        batch_op.drop_column('name')

    # ### end Alembic commands ###
