"""job apply status fixed

Revision ID: 625198eacd18
Revises: 454ca0027626
Create Date: 2023-04-24 13:44:20.143375

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '625198eacd18'
down_revision = '454ca0027626'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_application', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=postgresql.ENUM('submited', 'reviewed', 'interview', 'offered', 'rejected', name='jobapplicationstatus'),
               type_=sa.String(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_application', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('submited', 'reviewed', 'interview', 'offered', 'rejected', name='jobapplicationstatus'),
               existing_nullable=False)

    # ### end Alembic commands ###
