"""job application

Revision ID: 7bb9d6ce548f
Revises: c0cee112ff47
Create Date: 2023-04-24 11:35:58.484218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bb9d6ce548f'
down_revision = 'c0cee112ff47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_application',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('contact_number', sa.Integer(), nullable=False),
    sa.Column('contact_email', sa.String(length=120), nullable=False),
    sa.Column('resume', sa.Text(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('reply', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('submited', 'reviewed', 'interview', 'offered', 'rejected', name='jobapplicationstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_application', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_application_contact_email'), ['contact_email'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_application_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_application_updated_at'), ['updated_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_application', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_application_updated_at'))
        batch_op.drop_index(batch_op.f('ix_job_application_created_at'))
        batch_op.drop_index(batch_op.f('ix_job_application_contact_email'))

    op.drop_table('job_application')
    # ### end Alembic commands ###
