"""company_table

Revision ID: 7c20fd54fdd7
Revises: 6092228cc420
Create Date: 2023-04-14 14:18:36.327944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c20fd54fdd7'
down_revision = '6092228cc420'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_company_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_company_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_company_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_company_username'))
        batch_op.drop_index(batch_op.f('ix_company_name'))
        batch_op.drop_index(batch_op.f('ix_company_email'))

    op.drop_table('company')
    # ### end Alembic commands ###
