"""foreign table of job 12many

Revision ID: b9938210b2a5
Revises: 11b134d0e18c
Create Date: 2023-04-18 15:00:36.406925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9938210b2a5'
down_revision = '11b134d0e18c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_category')
    op.drop_table('job_location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_location',
    sa.Column('job_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('location_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], name='job_location_job_id_fkey'),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], name='job_location_location_id_fkey')
    )
    op.create_table('job_category',
    sa.Column('job_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], name='job_category_category_id_fkey'),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], name='job_category_job_id_fkey')
    )
    # ### end Alembic commands ###
